version: "3"
services:
  backend:
    image: arbengrepi/julkinen:backend
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    image: arbengrepi/julkinen:frontend
    ports:
      - "8080:80"
