version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
